Fix hostname setting for Debian or other distros where hostnamectl does not work.

diff --git a/google_config/bin/google_set_hostname b/google_config/bin/google_set_hostname
--- a/google_config/bin/google_set_hostname
+++ b/google_config/bin/google_set_hostname
@@ -40,6 +40,11 @@ if [ -n "$new_host_name" ]; then
   hostnamectl=$( which hostnamectl 2> /dev/null )
   if [ -x "$hostnamectl" ]; then
     $hostnamectl set-hostname "$new_host_name"
+    if [ $? -ne 0 ]; then
+      # Fallback to use hostname. hostnamectl can fail, for example, if dbus is
+      # not installed as it is not in Debian by default.
+      hostname "${new_host_name%%.*}"
+    fi
   else
     # Assume hostname command exists.
     hostname "${new_host_name%%.*}"
