code cleanup and standardizing in gce-disk-expand

diff --git a/packages/gce-disk-expand/src/usr/share/initramfs-tools/scripts/local-premount/expand_rootfs b/packages/gce-disk-expand/src/usr/share/initramfs-tools/scripts/local-premount/expand_rootfs
--- a/packages/gce-disk-expand/src/usr/share/initramfs-tools/scripts/local-premount/expand_rootfs
+++ b/packages/gce-disk-expand/src/usr/share/initramfs-tools/scripts/local-premount/expand_rootfs
@@ -3,70 +3,54 @@
 PREREQ=""
 prereqs()
 {
-	echo "$PREREQ"
+  echo "$PREREQ"
 }
 case $1 in
-# get pre-requisites
-prereqs)
-	prereqs
-	exit 0
-	;;
+  prereqs)
+    prereqs
+    exit 0
+    ;;
 esac
 
 . /scripts/functions
+. /local-premount/expandfs-lib.sh
 
-if ! real_root=$(resolve_device "${ROOT}"); then
-	log_failure_message "Failed to resolve root device for \"${ROOT}\""
+if ! rootdev=$(resolve_device "${ROOT}"); then
+  log_failure_message "Failed to resolve root device for \"${ROOT}\""
 fi
 
-if ! fs_type=$(get_fstype "${real_root}"); then
-	log_failure_message "Failed to determine fstype for \"${real_root}\""
+if ! fs_type=$(get_fstype "${rootdev}"); then
+  log_failure_message "Failed to determine fstype for \"${rootdev}\""
 fi
 
-rootdisk=${real_root%%[0-9]*}
-partnum=${real_root##$rootdisk}
-
-if parted -sm "$rootdisk" print 2>&1 | grep "fix the GPT"; then
-	parted -m ---pretend-input-tty "$rootdisk" print Fix  # Ugly hack
-        if parted -sm "$rootdisk" print 2>&1 | grep "fix the GPT"; then
-		log_failure_msg "Failed to correct GPT label on ${rootdisk}. Not resizing!"
-		exit 1
-	else
-		log_success_msg "Corrected GPT label on ${rootdisk}."
-	fi
+if ! out=$(get_partition "$rootdev"); then
+  echo "Failed to detect disk and partition info: ${out}"
+  exit 0
 fi
 
+disk=${out%:*}
+partnum=${out#*:}
 
-if ! parted -sm "$rootdisk" print | tail -1 | grep -q "^${partnum}:"; then
-	log_failure_msg "Root partition is not final partition on disk. Not resizing!"
-	exit 1
+if ! parted_needresize "$rootdisk" "$partnum"; then
+  exit 0
 fi
 
-if ! out=$(parted -sm "$rootdisk" -- resizepart "$partnum" -1); then
-	log_failure_msg "Failed to resize part ${partnum} on ${rootdisk}: ${out}"
-	exit 1
+echo "Resizing disk ${rootdev}"
+
+if ! out=$(parted_fix_gpt); then
+  echo "$out"
+  exit 0
 fi
 
-case "${fs_type}" in
-       	xfs)  
-		log_info_msg "xfs filesystems must be mounted to be resized, deferring to local-bottom/xfs_growfs"
-		;;
-       	ext*) 
-                log_begin_msg "Resizing ${fs_type} filesystem on ${real_root}"
-		if ! out=$(echo resize2fs "${real_root}"); then
-			log_failure_msg "resize2fs \"${real_root}\" failed:\n${out}"
-			exit 1
-		else
-			log_end_msg
-		fi
-	       	;;
-       	*)
-		echo "Unsupported filesystem type,  unable to expand size."
-		exit 1
-		;;
-esac
-
-
-log_success_msg "This is a success message containing real_root=${real_root}, fs_type=${fs_type}"
-
-exit 0
+if parted --help|grep -q 'resizepart'; then
+  if ! out=$(parted_resizepart "$disk" "$partnum"); then
+    echo "Failed to resize partition: ${out}"
+    exit 0
+  fi
+else
+  echo "parted doesn't support 'resizepart' command, trying rm&&mkpart"
+  if ! out=$(parted_resize_mkpart "$disk" "$partnum"); then
+    echo "Failed to resize partition: ${out}"
+    exit 0
+  fi
+fi
